spring.application.name=notification-communication
server.port=8081

# =================================
# EUREKA DISCOVERY
# =================================
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.lease-renewal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=30

# =================================
# CONFIGURATION EMAIL (Gmail)
# =================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rifaiiislam@gmail.com
spring.mail.password=ntsd bngj jwbg ylen
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =================================
# CONFIGURATION KAFKA
# =================================
spring.kafka.bootstrap-servers=localhost:9092
app.kafka.topics.notifications=doctorate-notifications
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.acks=all

# =================================
# CONFIGURATION MARIADB
# =================================
spring.datasource.url=jdbc:mariadb://localhost:3306/notification_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Meryem
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true

# =================================
# ACTUATOR
# =================================
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

# =================================
# LOGGING
# =================================
logging.level.ma.emsi.notification_communication=DEBUG
logging.level.org.springframework.kafka=INFO
logging.level.org.apache.kafka=WARN