spring.application.name=eureka-server
server.port=8761

# Le serveur Eureka ne s'enregistre pas lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuration du serveur - Mode développement
# Self-preservation activé (recommandé même en dev)
eureka.server.enable-self-preservation=true
eureka.server.eviction-interval-timer-in-ms=5000
eureka.server.response-cache-update-interval-ms=3000

# Dashboard Eureka
eureka.dashboard.enabled=true
eureka.dashboard.path=/

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
